# Generated by Django 5.1.7 on 2025-03-12 13:48

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0002_currency_alter_branch_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='City Name')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
            ],
            options={
                'verbose_name_plural': 'Cities',
            },
        ),
        migrations.CreateModel(
            name='VehicleType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Vehicle Type')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
            ],
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Activity Name')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.company', verbose_name='Company')),
                ('cities', models.ManyToManyField(to='records.city', verbose_name='Cities')),
            ],
            options={
                'verbose_name': 'Activity',
                'verbose_name_plural': 'Activities',
            },
        ),
        migrations.CreateModel(
            name='ActivityCost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Price')),
                ('valid_until', models.DateField(verbose_name='Valid Until')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='records.activity', verbose_name='Activity')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.company', verbose_name='Company')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='activity_costs', to='companies.currency', verbose_name='Currency')),
            ],
        ),
        migrations.CreateModel(
            name='ActivityCostHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valid_from', models.DateField(verbose_name='Valid From')),
                ('valid_until', models.DateField(verbose_name='Valid Until')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('activity_cost', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_history', to='records.activitycost')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='companies.currency')),
            ],
            options={
                'verbose_name': 'Activity Cost History',
                'verbose_name_plural': 'Activity Cost Histories',
                'ordering': ['-valid_from'],
            },
        ),
        migrations.CreateModel(
            name='ActivitySupplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Supplier Name')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.company', verbose_name='Company')),
                ('cities', models.ManyToManyField(to='records.city', verbose_name='Service Cities')),
            ],
        ),
        migrations.AddField(
            model_name='activitycost',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='records.activitysupplier', verbose_name='Supplier'),
        ),
        migrations.CreateModel(
            name='BuyerCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Company Name')),
                ('short_name', models.CharField(max_length=50, unique=True, verbose_name='Short Name')),
                ('contact', models.CharField(max_length=255, verbose_name='Contact')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.company', verbose_name='Company')),
            ],
            options={
                'verbose_name_plural': 'Buyer Companies',
            },
        ),
        migrations.CreateModel(
            name='Guide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Guide Name')),
                ('phone', models.CharField(max_length=20, verbose_name='Phone Number')),
                ('document_no', models.CharField(max_length=50, verbose_name='Document Number')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('cities', models.ManyToManyField(to='records.city', verbose_name='Cities')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.company', verbose_name='Company')),
            ],
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Hotel Name')),
                ('single_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Single Room Price')),
                ('double_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Double Room Price')),
                ('triple_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Family Room Price')),
                ('valid_until', models.DateField(verbose_name='Valid Until')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='records.city', verbose_name='City')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.company', verbose_name='Company')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='hotels', to='companies.currency', verbose_name='Currency')),
            ],
        ),
        migrations.CreateModel(
            name='HotelPriceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valid_from', models.DateField(verbose_name='Valid From')),
                ('valid_until', models.DateField(verbose_name='Valid Until')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('single_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('double_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('triple_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='companies.currency')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_history', to='records.hotel')),
            ],
            options={
                'verbose_name': 'Hotel Price History',
                'verbose_name_plural': 'Hotel Price Histories',
                'ordering': ['-valid_from'],
            },
        ),
        migrations.CreateModel(
            name='Museum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Museum Name')),
                ('local_price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Local Price')),
                ('foreign_price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Foreign Price')),
                ('valid_until', models.DateField(verbose_name='Valid Until')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='records.city', verbose_name='City')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.company', verbose_name='Company')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='museums', to='companies.currency', verbose_name='Currency')),
            ],
        ),
        migrations.CreateModel(
            name='MuseumPriceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valid_from', models.DateField(verbose_name='Valid From')),
                ('valid_until', models.DateField(verbose_name='Valid Until')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('local_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('foreign_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='companies.currency')),
                ('museum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_history', to='records.museum')),
            ],
            options={
                'verbose_name': 'Museum Price History',
                'verbose_name_plural': 'Museum Price Histories',
                'ordering': ['-valid_from'],
            },
        ),
        migrations.CreateModel(
            name='NoVehicleTour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Tour Name')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='records.city', verbose_name='City')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.company', verbose_name='Company')),
            ],
        ),
        migrations.CreateModel(
            name='Tour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Tour Name')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.company', verbose_name='Company')),
                ('end_city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tour_ends', to='records.city', verbose_name='End City')),
                ('start_city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tour_starts', to='records.city', verbose_name='Start City')),
            ],
        ),
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Transfer Name')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.company', verbose_name='Company')),
                ('end_city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfer_ends', to='records.city', verbose_name='End City')),
                ('start_city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfer_starts', to='records.city', verbose_name='Start City')),
            ],
        ),
        migrations.CreateModel(
            name='VehicleCost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_cost', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Car Cost')),
                ('minivan_cost', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Minivan Cost')),
                ('minibus_cost', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Minibus Cost')),
                ('midibus_cost', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Midibus Cost')),
                ('bus_cost', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Bus Cost')),
                ('valid_until', models.DateField(verbose_name='Valid Until')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.company', verbose_name='Company')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vehicle_costs', to='companies.currency', verbose_name='Currency')),
                ('tour', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='records.tour', verbose_name='Tour')),
                ('transfer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='records.transfer', verbose_name='Transfer')),
            ],
        ),
        migrations.CreateModel(
            name='VehicleCostHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valid_from', models.DateField(verbose_name='Valid From')),
                ('valid_until', models.DateField(verbose_name='Valid Until')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('car_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('minivan_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('minibus_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('midibus_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('bus_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='companies.currency')),
                ('vehicle_cost', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_history', to='records.vehiclecost')),
            ],
            options={
                'verbose_name': 'Vehicle Cost History',
                'verbose_name_plural': 'Vehicle Cost Histories',
                'ordering': ['-valid_from'],
            },
        ),
        migrations.CreateModel(
            name='VehicleSupplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Supplier Name')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('cities', models.ManyToManyField(to='records.city', verbose_name='Service Cities')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.company', verbose_name='Company')),
            ],
        ),
        migrations.AddField(
            model_name='vehiclecost',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='records.vehiclesupplier', verbose_name='Supplier'),
        ),
    ]
