# Generated by Django 5.1.7 on 2025-03-12 13:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_currency_alter_branch_options_and_more'),
        ('records', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='museum',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.city', verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='end_city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfer_ends', to='companies.city', verbose_name='End City'),
        ),
        migrations.AlterField(
            model_name='novehicletour',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.city', verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.city', verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='start_city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfer_starts', to='companies.city', verbose_name='Start City'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='start_city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tour_starts', to='companies.city', verbose_name='Start City'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='end_city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tour_ends', to='companies.city', verbose_name='End City'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='cities',
            field=models.ManyToManyField(to='companies.city', verbose_name='Cities'),
        ),
        migrations.AlterField(
            model_name='activitysupplier',
            name='cities',
            field=models.ManyToManyField(to='companies.city', verbose_name='Service Cities'),
        ),
        migrations.AlterField(
            model_name='guide',
            name='cities',
            field=models.ManyToManyField(to='companies.city', verbose_name='Cities'),
        ),
        migrations.AlterField(
            model_name='vehiclesupplier',
            name='cities',
            field=models.ManyToManyField(to='companies.city', verbose_name='Service Cities'),
        ),
        migrations.DeleteModel(
            name='City',
        ),
    ]
